### ISSUE TITLE
UserId always seems to be set to test_user_${defaultTargetPlatform.name}

### ISSUE THREAD

**Issue by daniel-kane-everbridge-com** [maxim-saplin/ambilytics#2]
There is a line in lib\src\ambilytics.dart the creates the AmbilyticsSession with a userId set to 'test_user_${defaultTargetPlatform.name}'.  I might be reading it wrong but I think it should be ambiUserId instead?

https://github.com/maxim-saplin/ambilytics/blob/099ac3e6f1515815fe2f5d2eb2cd987acc6cff12/lib/src/ambilytics.dart#L120

**Comment by maxim-saplin** [comment]
Thanks! Indeed the user ID for GA4/Measurement Protocol was broken. Fixed and pushed to pub.dev already.
