### ISSUE TITLE
use only MP for mac & windows

### ISSUE THREAD

**Issue by alexvoina** [maxim-saplin/ambilytics#6]
Hey, 

I'm looking for a minimal way to send a very basic event from my flutter desktop app (mac & windows) to my GA4 property. 

I don't intend to add more events & use it for actual analytics, since I'm using Sentry for that, I only want to send an event to optimize my Google Ads campaign. 

Does this plugin always build the firebase sdk for macOS? I don't want to add unused dependencies to my project. 

If this plugin is too much for my requirements, and I would be better off by copying only the MP part, I would be very thankful if you could point me to the code that needs to be stripped from here. 

Thanks!

**Comment by maxim-saplin** [comment]
The plugin is essentially one file, should be rady to strip out Firebase and leave the HTTP/GA4 part

**Comment by alexvoina** [comment]
thanks!

**Comment by maxim-saplin** [comment]
Nope, you better test it
