### ISSUE TITLE
Unexpected breaking change in patch version 1.0.7

### ISSUE THREAD

**Issue by JumpingLemons** [maxim-saplin/ambilytics#8]
Hi, the way our project is setup we are using a package that depends on ambilytics, the package we're using uses a caret `^` on the version like so:

```
dependencies:
  ambilytics: ^1.0.5
``` 

This is pretty common in the flutter community and works well with proper semantic versioning and it will automatically update minor and patch versions.

The issue is that version 1.0.6 introduced a breaking change the api of `sendEvent`
From
`void sendEvent({required String name, Map<String, Object?>? parameters}) {`
to
`void sendEvent({required String name, Map<String, Object>? parameters}) {`

This means that anyone currently using that api and supplying the old type will find their builds suddenly break.
This should only be done is major version updates.

Its an easy work around using this until the package we depend on updates
```
dependency_overrides:
  ambilytics: 1.0.5
```

But this adds code unrelated to our project, which isn't ideal.

**Comment by maxim-saplin** [comment]
Thanks for pointing out, 1.0.7 must have been 1.1.0 instead... Yet I don't think there's any fix for that issue, as the package is already published to pub.dev... Other than creating version 1.0.8 reverting the firebase dependency and creating a separate 1.1.0 version with newer firebase - which might complicate things
